### ISSUE TITLE
Shows   'UNVERSIONED'

### ISSUE THREAD

**Issue by WillDent** [expo/sentry-expo#13]
Not 100% sure but looks like you're looking for ReleaseId in the manifest.  But I don't see where this is being populated.  I added this to my app.json in hopes the version of my software would show but it is not.  Below is what I have but to no avail, it shows UNVERSIONED inside of Sentry's dashboard.  Using Expo SDK 20, iOS Simulator, using Sentry-Expo 1.6.

 ``{
  "expo": {
    "sdkVersion": "20.0.0",
    "name": "Dry Dock",
    "version":"1.0.0",
    "icon": "./appicon.png",
    "description": "Leading Dry Dock Logistics - Worldwide",
    "slug":"DryDockLogistics",
    "privacy": "unlisted",
    "revisionId": "1.0.0",
    "ios": {
        "bundleIdentifier": "ly.dent.3strand.ddgl"
      },
      "android": {
        "package": "ly.dent.3strand.ddgl"
      },
    "hooks": {
   "postPublish": [
     {
       "file": "sentry-expo/upload-sourcemaps",
       "config": {
         "organization": "Three Strand Business Solutions",
         "project": "Dry Dock Logistics Group",
       }
     }
   ]
 }
  }
}
``

**Comment by qbig** [comment]
<img width="1288" alt="screen shot 2018-03-05 at 11 40 50 am" src="https://user-images.githubusercontent.com/5563225/36956579-282ddc90-206a-11e8-8e02-248f6d8341e2.png">

**Comment by ximxim** [comment]
For me, on the simulator, the release shows up as UNVERSIONED. However, error from an actual device comes in with the release number.

**Comment by Reidweb1** [comment]
I'm testing on an actual device using `exp start --send-to <phone-number>` and I'm running into this issue as well. Line 19 in `index.js` of `sentry-expo` is setting "`release`" to `"UNVERSIONED"`. Here is the line:
```
const release = Constants.manifest.revisionId || 'UNVERSIONED';
```

I'm just wondering how/ where to set the `revisionId`

**Comment by iamhitarth** [comment]
Yup running into this issue as well. 

Any updates on this?

**Comment by iamhitarth** [comment]
From Expo documentation about [using Sentry](https://docs.expo.io/versions/v29.0.0/guides/using-sentry#publish-your-app-with-sourcemaps):
```
We automatically assign a unique release version for Sentry each time you hit publish, 
based on the version you specify in app.json and a release id on our backend -- this 
means that if you forget to update the version but hit publish, you will still get a 
unique Sentry release.
```
Why is this behaviour in place? 

Please do correct me if I am wrong, but it doesn't make sense to create a unique release for Sentry if the version in `app.json` for an Expo project hasn't changed - otherwise we run into this sort of an issue where Sentry records events/issues against that unique version while the Expo app releases show up under the version specified in `app.json`.
![image](https://user-images.githubusercontent.com/5507180/44773582-48e17c00-abb4-11e8-8992-e1447e3b23a5.png)

The way _I think_ it should be working is that the version for Sentry should mirror the version set in `app.json`. 

I have created a PR that does just that [here](https://github.com/expo/sentry-expo/pull/36).

**Comment by iamhitarth** [comment]
For anyone else that might be facing this issue, make sure you publish your app using `exp publish` - otherwise, you will keep getting `release` getting labelled as `UNVERSIONED`.
