### ISSUE TITLE
Sentry expo 2.1.2 (yargs-parser - low severity vulnerability)

### ISSUE THREAD

**Issue by veto221** [expo/sentry-expo#139]
Low severity vulnerability - dependency of sentry-expo: yarns-parser
More info: https://npmjs.com/advisories/1500
<img width="575" alt="Zrzut ekranu 2020-08-6 o 16 19 43" src="https://user-images.githubusercontent.com/8897035/89542969-a64ec080-d800-11ea-8c8d-97b8fd3febbd.png">

**Comment by cruzach** [comment]
Updated to the latest version of `@sentry/react-native` available (`1.7.1`) with the most recent release of `sentry-expo@3.0.0-rc3`, but looks like v11 of yargs-parser is still used in that version. However, I'm going to close this since it's low severity, and we'll wait for `@sentry/react-native` to upgrade
