### ISSUE TITLE
undefined is not an object (evaluating 'Sentry.options.logLeve')

### ISSUE THREAD

**Issue by 20matan** [expo/sentry-expo#16]
Hey guys, after i call `Sentry.clearContext()`, get this warning.
I used ios simulator.
seems like this line is causing the exception:

`  
static _log(...args) {
    if (Sentry.options.logLevel >= 2) {
       // eslint-disable-next-line
       console.log.apply(null, args);
    }
  }
`
in the if condition.
Did it happen to anyone else? maybe i did something wrong?

**Comment by HazAT** [comment]
Can you post your 
`Sentry.config('DSN').install();` call?

And which warning do you get?

**Comment by 20matan** [comment]
@HazAT 
I have this code
```
if (Settings.USE_RAVEN)
  Sentry.config(Settings.RAVEN_DSN).install()
```
which use a string depend on the environment of the app
do you need the specific dsn of mine?

and this is the warning i get:
`undefined is not an object (evaluating 'Sentry.options.logLeve')`

**Comment by folz** [comment]
Same thing was happening to me. Turns out I only configured Sentry in prod:

```javascript
if (!__DEV__) {
  Sentry.config(
    'MY_SENTRY_KEY',
  ).install();
}
```

but called `Sentry.setUserContext()` in dev and prod. The call in dev would fail because Sentry was never configured in that environment. Removing the `!__DEV__` check and relying on Expo's [Sentry disabled by default in dev](https://docs.expo.io/versions/latest/guides/using-sentry.html#disabled-by-default-in-dev) fixed this for me.
