### ISSUE TITLE
Sentry.Browser is not found in the typescript types for this library

### ISSUE THREAD

**Issue by lanman2000** [expo/sentry-expo#165]
It works at runtime but typescript hates it. Is this in the works to be fixed? 

Code is:
Sentry.Browser.configureScope(scope => {
    scope.setExtra('sessionURL', sessionURL);
});

Error is:

TS2339: Property 'Browser' does not exist on type 'typeof import("/Users/me/blahblah/node_modules/sentry-expo/dist/index")'.

**Comment by samtsai** [comment]
Seems like #151 changed the definitions a bit, not sure how it works in runtime because Browser is now broken out to its own file `sentry.web.js` and as far as I can tell is not exposed for importing. We might just have to have named exports from Sentry so you could do something like: `import { Sentry, SentryBrowser } from "sentry-expo"`

**Comment by lanman2000** [comment]
expo handles using the .web.js for the web build...

**Comment by lanman2000** [comment]
> import { Sentry, SentryBrowser } from "sentry-expo"

Right exactly I want to be able to do just that...

**Comment by chanonroy** [comment]
Also running into this issue. TS complains when trying to read property `Browser` on Sentry import.

**Comment by lanman2000** [comment]
Looks like it's fixed. When is the next bump please?

**Comment by cruzach** [comment]
fixed in https://github.com/expo/sentry-expo/commit/6f2abccba465f3992d13f9d24ba51daca6e776ae

**Comment by lanman2000** [comment]
👌👍🙌

**Comment by cruzach** [comment]
released in 3.1.2 (install with `yarn add sentry-expo@next`)

**Comment by n0mer** [comment]
@cruzach having same problem with "sentry-expo": "4.0.3"
