### ISSUE TITLE
For Sentry.captureMessage: undefined is not an object (evaluating 'a.stack[1]')

### ISSUE THREAD

**Issue by Dygerati** [expo/sentry-expo#18]
I'm a little befuddled--I'm attempting to use `Sentry.captureMessage` to log a message associated with a login issue, but Sentry.captureMessage itself is throwing an error (that is then, in turn, logged by Sentry). 

Here's the error with Stack/code/etc:
https://sentry.io/share/issue/3ab524a35e9a4ab7a65077957b2da21d/

The variable `msg` is just a string. Any thoughts?

EDIT: Also wanted to add that I'm using expo v22 and sentry-expo v1.6. The issue only occurs after published, not in dev or even running in prod mode locally.

**Comment by hrmoller** [comment]
I've been hunting the cause of this for a few days now and finally I find someone else experiencing it.

As OP I experience the bug in the login flow, when the server returns the response and the response is being parsed.

My request to Sentry looks as follows:
```js
Sentry.captureMessage('Error on login', {
  level: 'warning',
  extra: {
    result: json,
    user_id: credentieals.email,
    status: response.status
  }
});
```

But even reducing it to `Sentry.captureMessage('Error on login');` throws the error.

As OP I only see it in apps deployed to a physical device. Running it in simulator or on a connected device doesn't throw the error.

I'm targeting a Lenovo tablet running Android 6.0.1 and the rest of my setup looks as follows:
```json
"expo": "^22.0.2",
"moment": "^2.0.0",
"prop-types": "^15.5.10",
"raven-for-redux": "^1.1.1",
"react": "16.0.0-beta.5",
"react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",
"react-native-dropdownalert": "^3.1.2",
"react-redux": "^5.0.5",
"redux": "^3.7.2",
"redux-logger": "^3.0.6",
"redux-thunk": "^2.2.0",
 "sentry-expo": "^1.6.0"
```

For some reason I don't see any staktraces in Sentry otherwise I would happily share them. If anyone can tell me how to make Sentry show stacktraces I would very thankful. I'm uploading source maps already.

**Comment by MustansirZia** [comment]
I just started to use this package and I have the exact same thing. It behaves normally while running inside a simulator but when I deploy it to a standalone app the error occurs. 
This could be related stack traces since the error says `TypeError: undefined is not an object (evaluating 'a.stack[1]')`. 
Any help will be appreciated!

**Comment by hrmoller** [comment]
@MustansirZia you might be right about the stacktraces, it could very well be related to these lines https://github.com/expo/sentry-expo/blob/master/index.js#L143-L157

Very often I see this error logged `TypeError: undefined is not an object (evaluating 'n.frames')` when the error you mention is logged. They're logged separately and usually it happens when one or modals are transitioning.

It should be pretty easy to debug the lines mentioned above if it's possible to fork this lib and use `npm link` if that command works in React Native/Expo?

**Comment by MustansirZia** [comment]
@hrmoller I wouldn't use this repo if it wasn't for Expo. If you want to do `react-native link` you need to start a new project using the old `react-native init` command or detach your Expo app. In that case, it's probably better to use [react-native-sentry](https://github.com/getsentry/react-native-sentry) directly without Expo intervention. 
In the meanwhile, if I get time, I may try to fork this repo and see what's going on. Till then let's hope the contributor gets interested too. I don't want to detach my app so I really want this to work.

**Comment by hrmoller** [comment]
Oh, I totally agree with you. I did not mean `react-native link` but `npm link` to symlink `sentry-expo` into my app for debug purpose.

**Comment by MustansirZia** [comment]
`npm link` should work after forking, yes.

**Comment by hrmoller** [comment]
After upgrading expo(23.x.x), react and sentry-expo to latest (allowed) releases I can’t reproduce this issue anymore.

**Comment by duhaime** [comment]
@brentvatne @cruzach could we reopen this issue? I have the following versions:

```
    "expo": "^39.0.0",
    "expo-cli": "^3.27.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "sentry-expo": "latest",
```

Inside my top-level component I have:

```
import * as Sentry from 'sentry-expo'

Sentry.init({
  dsn: 'https://hash@sentry.io/integer',
  enableInExpoDevelopment: true,
  debug: true,
  release: Constants.manifest.revisionId,
});
```

Then, inside another component, I have:

```
import * as Sentry from 'sentry-expo'
```

Running `Sentry.captureMessage(' * exception')` in a function within that component throws:

> Sentry.captureException is not a function. (In 'Sentry.captureMessage(' * exception')', 'Sentry.captureMessage' is undefined)

Errors thrown by my app appear in my Sentry dashboard. I'm just trying to manually log some text to figure out why some `AsyncStorage.getItem()` calls are working in development but failing on a standalone build, but I'm not currently able to log any messages. For what it's worth, I also get an exception indicating `Sentry.captureException` is not a function. 

Any pointers or advice you can offer on this question would be hugely helpful!

**Comment by cruzach** [comment]
@duhaime there were breaking changes involved in the update to v3, you should read the docs for more info- https://docs.expo.io/guides/using-sentry/#install-and-configure-sentry

```import * as Sentry from 'sentry-expo';

Sentry.init({
  dsn: 'YOUR DSN HERE',
  enableInExpoDevelopment: true,
  debug: true, // Sentry will try to print out useful debugging information if something goes wrong with sending an event. Set this to `false` in production.
});

// Access any @sentry/react-native exports via:
Sentry.Native.*

// Access any @sentry/browser exports via:
Sentry.Browser.*
```

(you need to replace `Sentry.captureMessage` with `Sentry.Native.captureMessage`

**Comment by duhaime** [comment]
@cruzach spectacular, thanks very much for your quick follow up!

**Comment by stesvis** [comment]
I am getting this error in 2023 using:
- `"sentry-expo": "~6.2.0"`
- `"expo": "^48.0.19"`
- `"react-native": "0.71.8"`

It happens the second time I call `Sentry.Native.captureMessage('test')`.

Any solution yet?

**Comment by daniel-davy** [comment]
@stesvis same here! any help?
