### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Sentry"

### ISSUE THREAD

**Issue by nicolelopezfeliz** [expo/sentry-expo#278]
### Summary

Whenever I try to build a new native shell for IOS devices in my expo app I get CocoaPods could not find compatible versions for pod "Sentry". I tried downgrading @sentry/react-native and the sentry-expo packages but I get the same error but with different package dependency's. 

My sentry-expo version: "sentry-expo": "~5.0.0"
My @sentry/react-native version: "@sentry/react-native": "^4.1.3"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46

### Environment

Installing pods
2
Using Expo modules
3
Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/expo/.nvm/versions/node/v14.18.0/bin/node
4
Auto-linking React Native modules for target `aLexDev`: RNCAsyncStorage, RNSVG, RNScreens, RNSentry, lottie-ios, lottie-react-native, react-native-agora, react-native-safe-area-context, and react-native-webview
5
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
6
Analyzing dependencies
7
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
8
[Codegen] Found FBReactNativeSpec
9
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
10
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
11
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
12
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
13
[!] CocoaPods could not find compatible versions for pod "Sentry":
14
  In snapshot (Podfile.lock):
15
    Sentry (= 7.3.0)
16
17
  In Podfile:
18
    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 4.2.3, which depends on
19
      Sentry (= 7.23.0)
20
21
22
You have either:
23
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
24
 * changed the constraints of dependency `Sentry` inside your development pod `RNSentry`.
25
   You should run `pod update Sentry` to apply changes you've made.
26
Error: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add the "cache.key" field (it can be set to any value) in the build profile in eas.json to invalidate the cache.
  - Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.

### Reproducible demo or steps to reproduce from a blank project

I installed sentry-expo and @sentry/react-native. Then I created a new build I expo eas.

**Comment by kbrandwijk** [comment]
Could you try again with `eas build --clear-cache`? Also make sure you're updated to the latest version, which uses `@sentry/react-native@4.2.2`

**Comment by nicolehackberry** [comment]
@kbrandwijk I did update to the latest version now, I also tried to clear my caches but this did not work, I get the following errors: 

`Installing pods
2
Using Expo modules
3
Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/expo/.nvm/versions/node/v14.18.0/bin/node
4
Auto-linking React Native modules for target `aLexDev`: RNCAsyncStorage, RNSVG, RNScreens, RNSentry, lottie-ios, lottie-react-native, react-native-agora, react-native-safe-area-context, and react-native-webview
5
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
6
Analyzing dependencies
7
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
8
[Codegen] Found FBReactNativeSpec
9
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
10
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
11
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
12
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
13
[!] CocoaPods could not find compatible versions for pod "Sentry":
14
  In snapshot (Podfile.lock):
15
    Sentry (= 7.3.0)
16
17
  In Podfile:
18
    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 4.2.2, which depends on
19
      Sentry (= 7.22.0)
20
21
22
You have either:
23
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
24
 * changed the constraints of dependency `Sentry` inside your development pod `RNSentry`.
25
   You should run `pod update Sentry` to apply changes you've made.
26
Error: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add the "cache.key" field (it can be set to any value) in the build profile in eas.json to invalidate the cache.
  - Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.`

**Comment by kbrandwijk** [comment]
If `eas build --clear-cache` doesn't work, then you can also try specifying a different cache key in your build profile. https://docs.expo.dev/build-reference/eas-json/#cache

**Comment by jamesedmonston** [comment]
@nicolehackberry did you find a solution to this?

**Comment by grossadamm** [comment]
@jamesedmonston I running in the same issue where things were working on `eas` servers but not `--local` until I ran 

```
expo prebuild -p ios
npx expo run:ios
```

I noticed when prebuild ran, it had some issue with installing pods, but the live logs removed the message once the issue was resolved. I think it may have installed a new version of cocoa pods or something? I don't know.

The error was replaced with
```
 Installed pods and initialized Xcode workspace.
```

**Comment by julius-lae** [comment]
Any update on this?

**Comment by parniekovvakoms** [comment]
The same problem with local build

**Comment by vic-pic** [comment]
HI all,
is there any news about this issue? I have the same problem.

Thanks Vincenzo

**Comment by tomrom-pomelo** [comment]
Running `pod repo update` before running the build resolved this issue for me locally

**Comment by eliasmelgaco** [comment]
as iI updated the sentry manually I had some problems with the Sentry on pod. To solve it, I removed the Podfile.lock and then ran `pod install` in the /ios folder (I'm using the flutter, but, It seems the same problem)

**Comment by ToshKoevoets** [comment]
In my case cocaopods offered the correct solution:
```
pod install --repo-update
```

**Comment by saoud77** [comment]
Try to update the Sentry/HybridSDK pod version in the podfile.lock file. You can do this by running the following command:

`pod update Sentry/HybridSDK`

**Comment by mzruiz** [comment]
Removing the existing `Podfile.lock` and running `pod install` worked for me

**Comment by KennyCallegari** [comment]
For me nothing above worked. But I rebased my brach on master which I recently upgraded cocoapods from 1.11.3 to 1.12.1.

After that, I did `rm -f Podfile.lock; pod install --repo-update` and it worked

**Comment by armaganwork** [comment]
I have changed my platform from platform :ios, '11.0' to platform :ios, '13.0' and it works now.

**Comment by fwdillema** [comment]
Had same issue with. --local build and did not want to use prebuild to create an ios directory. The following worked for me instead:

sudo rm -rf ~/.cocoapods/repos

**Comment by kaneda-fr** [comment]
> [@jamesedmonston](https://github.com/jamesedmonston) I running in the same issue where things were working on `eas` servers but not `--local` until I ran
> 
> ```
> expo prebuild -p ios
> npx expo run:ios
> ```
> 
> I noticed when prebuild ran, it had some issue with installing pods, but the live logs removed the message once the issue was resolved. I think it may have installed a new version of cocoa pods or something? I don't know.
> 
> The error was replaced with
> 
> ```
>  Installed pods and initialized Xcode workspace.
> ```

This worked for me. Thanks !
