### ISSUE TITLE
stack trace not generated for non fatal exceptions on android

### ISSUE THREAD

**Issue by alxyuu** [expo/sentry-expo#4]
When an exception is caught by sentry but is not fatal (e.g. directly calling Sentry.captureException) on android, a stack trace is not generated. Calling Sentry.captureException does generate a stack trace on ios.

**Comment by larkintuckerllc** [comment]
Seem to be having similar issues (currently using 1.9.0); did use `create-react-native-app` to bootstrap project.  Can confirm that Sentry releases with the artifacts (e.g., ~/main.android.bundle and ~/main.android.map) are being created. 

I see the errors (being tagged to the right release) appear (both uncaught and caught) in Sentry.

The caught ones look like:

```
Error: Caught
  at ? ([native code])
  at ? ([native code])
  at ? ([native code])
  at ? ([native code])
  at forEach([native code])
```

The uncaught ones look like:

```
Non-Error exception captured with keys: column, context, handleOnPress, line…
```

**Comment by brentvatne** [comment]
can you ask sentry support about this? they would have more info

**Comment by pwlmaciejewski** [comment]
I'm having this issue on android as well. `"sentry-expo": "2.0.1",`

Errors handled by the global handler have a full stack trace where the others (i.e. `Sentry.captureException()`) are stripped out of any meaningful data so you end up with something like this:
![Error  test2](https://user-images.githubusercontent.com/1276139/72399361-41d5f200-3746-11ea-9d37-2c261002743b.png)

I did some code digging and you need to rewrite stack trace on android for sentry, otherwise, it won't parse it. It's done here explicitly:

https://github.com/expo/sentry-expo/blob/master/index.js#L60-L65

As far as I understand the issue, the stack trace replacement should also be implemented in all the other places including `captureExpection`?

**Comment by cruzach** [comment]
I believe this was just recently fixed in the newest version of `@sentry/react-native`, v2.2.2 

To get this fix in `sentry-expo`, you'll just need to remove your `node_modules` and lockfile and reinstall `sentry-expo@next`, since it should automatically pull in the newest version of `@sentry/react-native` (unless it's a breaking change)

Let me know if the issue persists and include your versions of `@sentry/react-native` and `sentry-expo`
